POST http://localhost:9000/transfer HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGExNjhhYjZkOWI4MWRjMzA4NWRkZCIsInVzZXJJZCI6Ijk4NzY1NjczIiwiaWF0IjoxNzEwMjY0NDczLCJleHAiOjE3MTAyNjgwNzN9.af6mCSClZwK_otYj-b_wdW60OQrHLmgyF5lxBEQQTtM


{
    "userId": "98765673",
    "receiverId": "12345678",
    "amount": 100
}