apiVersion: apps/v1
kind: Deployment
metadata:
 name: login-deployment
spec:
 replicas: 1
 selector:
    matchLabels:
      app: login
 template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: rohare999/login:latest
        ports:
        - containerPort: 3000