GET http://localhost:3000/jwt-verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzEyYjBjMDFlOWFmZGE3ZGQyZjIxMyIsInVzZXJuYW1lIjoidXNlcjMiLCJpYXQiOjE3MDcxNjE4MDksImV4cCI6MTcwNzE2NTQwOX0.1-iacphaAAFGbbpySgiLRF7sM5xDjp62WAnz49UvSnw
