POST http://localhost:9000/get-balance HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGExNjhhYjZkOWI4MWRjMzA4NWRkZCIsInVzZXJJZCI6Ijk4NzY1NjczIiwiaWF0IjoxNzEwMjQ3MzUxLCJleHAiOjE3MTAyNTA5NTF9.39J6hTDcZpc1IEWCvH1FyewIehwtOETMeLx6XH3Ba8w